#include "wx/wx.h"
wxString* AcceleratorsDialogHtml() {
  wxString* output = new wxString();
  output->Alloc(7137);
  output->Append(wxT("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> \n"));
output->Append(wxT("<html xmlns=\"http://www.w3.org/1999/xhtml\"> \n"));
output->Append(wxT("  <head> \n"));
output->Append(wxT("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" /> \n"));
output->Append(wxT("	<style type='text/css'>\n"));
output->Append(wxT("		#wrapper {\n"));
output->Append(wxT("			width: 97.5%;\n"));
output->Append(wxT("			margin: 1%;\n"));
output->Append(wxT("			height: 500px;\n"));
output->Append(wxT("			overflow: auto;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		table, tr, td, div, span, p, input, body {\n"));
output->Append(wxT("			padding: 0;\n"));
output->Append(wxT("			margin: 0;\n"));
output->Append(wxT("			border-spacing: 0;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		body {\n"));
output->Append(wxT("			background-color: #F0F0F0;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		body, input.textfield {\n"));
output->Append(wxT("			font-family: Calibri;\n"));
output->Append(wxT("			font-size: 12px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		#mainTable {\n"));
output->Append(wxT("			border: 2px groove #FFF;\n"));
output->Append(wxT("			width: 500px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.toggleArrow {\n"));
output->Append(wxT("			height: 15px;\n"));
output->Append(wxT("			width: 15px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.menuItemLabel, .menuLabel, .defaultBinding {\n"));
output->Append(wxT("			padding: 1px 5px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.newBinding {\n"));
output->Append(wxT("			width: 100px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		.defaultBinding {\n"));
output->Append(wxT("			width: 100px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.odd {\n"));
output->Append(wxT("			background-color: #FAFAFA;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.even {\n"));
output->Append(wxT("			background-color: #E9E9E9;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		td {\n"));
output->Append(wxT("			border-top: 1px solid #CCC;\n"));
output->Append(wxT("			border-collapse: collapse;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.save {\n"));
output->Append(wxT("			padding: 2px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.level0 { padding-left: 0px; }\n"));
output->Append(wxT("		.level1 { padding-left: 15px; }\n"));
output->Append(wxT("		.level2 { padding-left: 30px; }\n"));
output->Append(wxT("		.level3 { padding-left: 45px; }\n"));
output->Append(wxT("		.level4 { padding-left: 60px; }\n"));
output->Append(wxT("		.level5 { padding-left: 75px; }\n"));
output->Append(wxT("		.level6 { padding-left: 90px; }\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.menuLabel {\n"));
output->Append(wxT("			font-weight: bold;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		.menuLabel a, .menuLabel a:visited {\n"));
output->Append(wxT("			color: black;\n"));
output->Append(wxT("			text-decoration: none;\n"));
output->Append(wxT("			padding-right: 5px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("	</style>\n"));
output->Append(wxT("</head>\n"));
output->Append(wxT("<body>\n"));
output->Append(wxT("<div id='wrapper'>\n"));
output->Append(wxT("	$1\n"));
output->Append(wxT("</div>\n"));
output->Append(wxT("<center>\n"));
output->Append(wxT("	<input type='button' value='Save' class='save' id='save' />\n"));
output->Append(wxT("</center>\n"));
output->Append(wxT("<script type='text/javascript' src='http://code.jquery.com/jquery-1.4.3.min.js'></script>\n"));
output->Append(wxT("<script type='text/javascript'>\n"));
output->Append(wxT("	// Show only the top level menus\n"));
output->Append(wxT("	$(\"tr\").hide();\n"));
output->Append(wxT("	$(\"tr.menu0\").show();\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	var state = {};\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	$(\"input.textfield\").keyup(function(e) {\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		var code = e.keyCode;\n"));
output->Append(wxT("		switch(code) {\n"));
output->Append(wxT("			case 16: state.shift = false; break;\n"));
output->Append(wxT("			case 17: state.control = false; break;\n"));
output->Append(wxT("			case 18: state.alt = false; break;\n"));
output->Append(wxT("			case 91: state.windows = false; break;\n"));
output->Append(wxT("			case 92: state.windows = false; break;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		e.preventDefault();\n"));
output->Append(wxT("		e.stopPropagation();\n"));
output->Append(wxT("		return false;\n"));
output->Append(wxT("	});\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	$(\"input.textfield\").keydown(function(e) {\n"));
output->Append(wxT("		var $this = $(this);\n"));
output->Append(wxT("		var data = $this.data('key');\n"));
output->Append(wxT("		if(!data) {\n"));
output->Append(wxT("			data = {};\n"));
output->Append(wxT("			$this.data('key', data);\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		var key1 = data.key1 || {};\n"));
output->Append(wxT("		data.key1 = key1;\n"));
output->Append(wxT("		var key2 = data.key2 || {};\n"));
output->Append(wxT("		data.key2 = key2;\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		var key = key1;\n"));
output->Append(wxT("		if(key.done) {\n"));
output->Append(wxT("			if(key2.done) {\n"));
output->Append(wxT("				$this.val(\"\");\n"));
output->Append(wxT("				key = key1 = data.key1 = {};\n"));
output->Append(wxT("				key2 = data.key2 = {};\n"));
output->Append(wxT("			} else {\n"));
output->Append(wxT("				key = key2;\n"));
output->Append(wxT("			}\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		var code = e.keyCode;\n"));
output->Append(wxT("		switch(code) {\n"));
output->Append(wxT("			case 16: state.shift = true; break;\n"));
output->Append(wxT("			case 17: state.control = true; break;\n"));
output->Append(wxT("			case 18: state.alt = true; break;\n"));
output->Append(wxT("			case 91: state.windows = true; break;\n"));
output->Append(wxT("			case 92: state.windows = true; break;\n"));
output->Append(wxT("			default:\n"));
output->Append(wxT("				key.control = state.control;\n"));
output->Append(wxT("				key.alt = state.alt;\n"));
output->Append(wxT("				key.shift = state.shift;\n"));
output->Append(wxT("				key.windows = state.windows;\n"));
output->Append(wxT("				key.code = code;\n"));
output->Append(wxT("				key.done = true;\n"));
output->Append(wxT("				break;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		if(key1.done) {\n"));
output->Append(wxT("			var str = toStr(key1);\n"));
output->Append(wxT("			if(key2.done) str += \" \"+toStr(key2)\n"));
output->Append(wxT("			$this.val(str);\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		e.preventDefault();\n"));
output->Append(wxT("		e.stopPropagation();\n"));
output->Append(wxT("		return false;\n"));
output->Append(wxT("	});\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	// Remove blank menus\n"));
output->Append(wxT("	for(var c = 247; c > 0; c--) {\n"));
output->Append(wxT("		if($('tr.menu'+c).length === 0) {\n"));
output->Append(wxT("			$('#menu'+c).closest('tr').remove();\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("	}\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	// Have to recursively close all submenus as well\n"));
output->Append(wxT("	function close(menu) {\n"));
output->Append(wxT("		var openSubMenus = $('tr.'+menu+':visible');\n"));
output->Append(wxT("		for(var c = 0; c < openSubMenus.length; c++) {\n"));
output->Append(wxT("			var link = $(openSubMenus[c]).find('a');\n"));
output->Append(wxT("			link.html(\"&rarr;\");\n"));
output->Append(wxT("			close(link.attr('id'));\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		openSubMenus.hide();\n"));
output->Append(wxT("	}\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	// Open menus when clicked\n"));
output->Append(wxT("	$(\"a.expand\").live('click', function() {\n"));
output->Append(wxT("			var id = $(this).attr('id');\n"));
output->Append(wxT("			var rows = $(\"tr.\"+id);\n"));
output->Append(wxT("			\n"));
output->Append(wxT("			if(rows.is(\":visible\")) {\n"));
output->Append(wxT("				close(id);\n"));
output->Append(wxT("				rows.hide();\n"));
output->Append(wxT("				$(this).html(\"&rarr;\");\n"));
output->Append(wxT("			} else {\n"));
output->Append(wxT("				rows.show();\n"));
output->Append(wxT("				$(this).html(\"&darr;\");\n"));
output->Append(wxT("			}\n"));
output->Append(wxT("			\n"));
output->Append(wxT("			$(\"tr:visible:even\").removeClass(\"odd\").addClass(\"even\");\n"));
output->Append(wxT("			$(\"tr:visible:odd\").removeClass(\"even\").addClass(\"odd\");\n"));
output->Append(wxT("	});\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	function toStr(key) {\n"));
output->Append(wxT("		var str = \"\";\n"));
output->Append(wxT("		if(key.control) str += \"Ctrl-\";\n"));
output->Append(wxT("		if(key.alt) str += \"Alt-\";\n"));
output->Append(wxT("		if(key.shift) str += \"Shift-\";\n"));
output->Append(wxT("		if(key.windows) str += \"Win-\";\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		if(key.code) {\n"));
output->Append(wxT("			var code = keyCodeToStr(key.code);\n"));
output->Append(wxT("			if(code && code.length > 0) {\n"));
output->Append(wxT("				str += code;\n"));
output->Append(wxT("				key.done = true;\n"));
output->Append(wxT("			}\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		return str;\n"));
output->Append(wxT("	}\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	function keyCodeToStr(code) {\n"));
output->Append(wxT("		if(code >= 48 && code <= 57 || code >= 65 && code <= 90) {\n"));
output->Append(wxT("			return String.fromCharCode(code);\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		switch(code) {\n"));
output->Append(wxT("			case 3: return \"CANCEL\";\n"));
output->Append(wxT("			case 8: return \"BACK\";\n"));
output->Append(wxT("			case 9: return \"TAB\";\n"));
output->Append(wxT("			case 12: return \"CLEAR\";\n"));
output->Append(wxT("			case 13: return \"RETURN\";\n"));
output->Append(wxT("			case 14: return \"ENTER\";\n"));
output->Append(wxT("			case 19: return \"PAUSE\";\n"));
output->Append(wxT("			case 20: return \"CAPITAL\";\n"));
output->Append(wxT("			case 27: return \"ESCAPE\";\n"));
output->Append(wxT("			case 32: return \"SPACE\";\n"));
output->Append(wxT("			case 33: return \"PGUP\";\n"));
output->Append(wxT("			case 34: return \"PGDN\";\n"));
output->Append(wxT("			case 35: return \"END\";\n"));
output->Append(wxT("			case 36: return \"HOME\";\n"));
output->Append(wxT("			case 37: return \"LEFT\";\n"));
output->Append(wxT("			case 38: return \"UP\";\n"));
output->Append(wxT("			case 39: return \"RIGHT\";\n"));
output->Append(wxT("			case 40: return \"DOWN\";\n"));
output->Append(wxT("			case 44: return \"PRINT\";\n"));
output->Append(wxT("			case 45: return \"INSERT\";\n"));
output->Append(wxT("			case 46: return \"DELETE\";\n"));
output->Append(wxT("			case 59: return \";\";\n"));
output->Append(wxT("			case 61: return \"=\";\n"));
output->Append(wxT("			case 93: return \"MENU\";\n"));
output->Append(wxT("			case 96: return \"\"; //num0\n"));
output->Append(wxT("			case 97: return \"\";\n"));
output->Append(wxT("			case 98: return \"\";\n"));
output->Append(wxT("			case 99: return \"\";\n"));
output->Append(wxT("			case 100: return \"\";\n"));
output->Append(wxT("			case 101: return \"\";\n"));
output->Append(wxT("			case 102: return \"\";\n"));
output->Append(wxT("			case 103: return \"\";\n"));
output->Append(wxT("			case 104: return \"\";\n"));
output->Append(wxT("			case 105: return \"\";//num9\n"));
output->Append(wxT("			case 106: return \"KP_MULTIPLY\";\n"));
output->Append(wxT("			case 107: return \"KP_ADD\";\n"));
output->Append(wxT("			case 108: return \"KP_SEPARATOR\";\n"));
output->Append(wxT("			case 109: return \"KP_SUBTRACT\";\n"));
output->Append(wxT("			case 110: return \"KP_DECIMAL\";\n"));
output->Append(wxT("			case 111: return \"KP_DIVICE\";\n"));
output->Append(wxT("			case 112: return \"F1\";\n"));
output->Append(wxT("			case 113: return \"F2\";\n"));
output->Append(wxT("			case 114: return \"F3\";\n"));
output->Append(wxT("			case 115: return \"F4\";\n"));
output->Append(wxT("			case 116: return \"F5\";\n"));
output->Append(wxT("			case 117: return \"F6\";\n"));
output->Append(wxT("			case 118: return \"F7\";\n"));
output->Append(wxT("			case 119: return \"F8\";\n"));
output->Append(wxT("			case 120: return \"F9\";\n"));
output->Append(wxT("			case 121: return \"F10\";\n"));
output->Append(wxT("			case 122: return \"F11\";\n"));
output->Append(wxT("			case 123: return \"F12\";\n"));
output->Append(wxT("			case 124: return \"F13\";\n"));
output->Append(wxT("			case 125: return \"F14\";\n"));
output->Append(wxT("			case 126: return \"F15\";\n"));
output->Append(wxT("			case 127: return \"F16\";\n"));
output->Append(wxT("			case 128: return \"F17\";\n"));
output->Append(wxT("			case 129: return \"F18\";\n"));
output->Append(wxT("			case 130: return \"F19\";\n"));
output->Append(wxT("			case 131: return \"F20\";\n"));
output->Append(wxT("			case 132: return \"F21\";\n"));
output->Append(wxT("			case 133: return \"F22\";\n"));
output->Append(wxT("			case 134: return \"F23\";\n"));
output->Append(wxT("			case 135: return \"F24\";\n"));
output->Append(wxT("			case 144: return \"NUM_LOCK\";\n"));
output->Append(wxT("			case 145: return \"SCOLL_LOCK\";\n"));
output->Append(wxT("			case 186: return \";\";\n"));
output->Append(wxT("			case 187: return \"=\";\n"));
output->Append(wxT("			case 188: return \",\";\n"));
output->Append(wxT("			case 189: return \"-\";\n"));
output->Append(wxT("			case 190: return \".\";\n"));
output->Append(wxT("			case 191: return \"/\";\n"));
output->Append(wxT("			case 192: return \"`\";\n"));
output->Append(wxT("			case 219: return \"[\";\n"));
output->Append(wxT("			case 220: return \"\\\\\";\n"));
output->Append(wxT("			case 221: return \"]\";\n"));
output->Append(wxT("			case 222: return \"'\";\n"));
output->Append(wxT("			//case : return \"\";\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		return \"\";\n"));
output->Append(wxT("	}\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	$(\"#save\").click(function() {\n"));
output->Append(wxT("		var bits = $(\"input.textfield\").map(function() { \n"));
output->Append(wxT("			var name = $(this).attr('name').replace(\"\\\"\", \"\\\\\\\"\");\n"));
output->Append(wxT("			var binding = $(this).val().replace(\"\\\"\", \"\\\\\\\"\");\n"));
output->Append(wxT("			if(binding.length == 0) return;\n"));
output->Append(wxT("			return [\"\\\"\", name, \"\\\"\", \":\", \"\\\"\", binding, \"\\\"\"].join(\"\");\n"));
output->Append(wxT("		});\n"));
output->Append(wxT("		var json = \"http://localhost/{\"+Array.prototype.join.call(bits, \",\")+\"}\";\n"));
output->Append(wxT("		window.location = json;\n"));
output->Append(wxT("	});\n"));
output->Append(wxT("</script>\n"));
output->Append(wxT("</body>\n"));
output->Append(wxT("</html>\n"));
  return output;
}