#include "wx/wx.h"
wxString* AcceleratorsDialogHtml() {
  wxString* output = new wxString();
  output->Alloc(4348);
  output->Append(wxT("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> \n"));
output->Append(wxT("<html xmlns=\"http://www.w3.org/1999/xhtml\"> \n"));
output->Append(wxT("  <head> \n"));
output->Append(wxT("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" /> \n"));
output->Append(wxT("	<style type='text/css'>\n"));
output->Append(wxT("		#wrapper {\n"));
output->Append(wxT("			width: 700px;\n"));
output->Append(wxT("			margin: 10px;\n"));
output->Append(wxT("			height: 500px;\n"));
output->Append(wxT("			overflow: auto;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		#left {\n"));
output->Append(wxT("			float: left;\n"));
output->Append(wxT("			width: 504px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		#right {\n"));
output->Append(wxT("			width: 175px;\n"));
output->Append(wxT("			float: left;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		table, tr, td, div, span, p, input, body {\n"));
output->Append(wxT("			padding: 0;\n"));
output->Append(wxT("			margin: 0;\n"));
output->Append(wxT("			border-spacing: 0;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		ul {\n"));
output->Append(wxT("			padding: 0;\n"));
output->Append(wxT("			margin: 0 0 0 20px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		body {\n"));
output->Append(wxT("			background-color: #F0F0F0;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		body, input.textfield {\n"));
output->Append(wxT("			font-family: Calibri;\n"));
output->Append(wxT("			font-size: 12px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		input.textfield {\n"));
output->Append(wxT("			margin: 1px 2px 1px 0;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		#mainTable {\n"));
output->Append(wxT("			border: 2px groove #FFF;\n"));
output->Append(wxT("			width: 500px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.toggleArrow {\n"));
output->Append(wxT("			height: 15px;\n"));
output->Append(wxT("			width: 15px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.menuItemLabel, .menuLabel, .defaultBinding {\n"));
output->Append(wxT("			padding: 1px 5px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.newBinding {\n"));
output->Append(wxT("			width: 100px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		.defaultBinding {\n"));
output->Append(wxT("			width: 100px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.odd {\n"));
output->Append(wxT("			background-color: #FAFAFA;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.even {\n"));
output->Append(wxT("			background-color: #E9E9E9;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		td {\n"));
output->Append(wxT("			border-top: 1px solid #CCC;\n"));
output->Append(wxT("			border-collapse: collapse;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.save {\n"));
output->Append(wxT("			padding: 2px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.level0 { padding-left: 0px; }\n"));
output->Append(wxT("		.level1 { padding-left: 15px; }\n"));
output->Append(wxT("		.level2 { padding-left: 30px; }\n"));
output->Append(wxT("		.level3 { padding-left: 45px; }\n"));
output->Append(wxT("		.level4 { padding-left: 60px; }\n"));
output->Append(wxT("		.level5 { padding-left: 75px; }\n"));
output->Append(wxT("		.level6 { padding-left: 90px; }\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		.menuLabel {\n"));
output->Append(wxT("			font-weight: bold;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		.menuLabel a, .menuLabel a:visited {\n"));
output->Append(wxT("			color: black;\n"));
output->Append(wxT("			text-decoration: none;\n"));
output->Append(wxT("			padding-right: 5px;\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		\n"));
output->Append(wxT("	</style>\n"));
output->Append(wxT("</head>\n"));
output->Append(wxT("<body>\n"));
output->Append(wxT("<div id='wrapper'>\n"));
output->Append(wxT("	<div id='left'>\n"));
output->Append(wxT("		$1\n"));
output->Append(wxT("	</div>\n"));
output->Append(wxT("	<div id='right'>\n"));
output->Append(wxT("		<strong>Examples:</strong>\n"));
output->Append(wxT("		<ul>\n"));
output->Append(wxT("			<li>Ctrl-A</li>\n"));
output->Append(wxT("			<li>Ctrl+A</li>\n"));
output->Append(wxT("			<li>Ctrl-X Ctrl-A</li>\n"));
output->Append(wxT("			<li>Ctrl-Alt-Win-Shift-Space</li>\n"));
output->Append(wxT("		</ul>\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		<strong>Notes:</strong>\n"));
output->Append(wxT("		<ul>\n"));
output->Append(wxT("			<li>Only the non-shift character for non-alpha characters works.  In other words, Ctrl-; and Ctrl-: are the same thing.</li>\n"));
output->Append(wxT("			<li>You can use these keys too:</li>\n"));
output->Append(wxT("		</ul>\n"));
output->Append(wxT("		\n"));
output->Append(wxT("		<ul style='list-style-type: none;'>\n"));
output->Append(wxT("			<li>BACK</li>\n"));
output->Append(wxT("			<li>CANCEL</li>\n"));
output->Append(wxT("			<li>CAPITAL</li>\n"));
output->Append(wxT("			<li>CLEAR</li>\n"));
output->Append(wxT("			<li>DELETE</li>\n"));
output->Append(wxT("			<li>DOWN</li>\n"));
output->Append(wxT("			<li>END</li>\n"));
output->Append(wxT("			<li>ENTER</li>\n"));
output->Append(wxT("			<li>ESCAPE</li>\n"));
output->Append(wxT("			<li>F1 -> F24</li>\n"));
output->Append(wxT("			<li>HOME</li>\n"));
output->Append(wxT("			<li>INSERT</li>\n"));
output->Append(wxT("			<li>KP_ADD</li>\n"));
output->Append(wxT("			<li>KP_DECIMAL</li>\n"));
output->Append(wxT("			<li>KP_DIVICE</li>\n"));
output->Append(wxT("			<li>KP_MULTIPLY</li>\n"));
output->Append(wxT("			<li>KP_SEPARATOR</li>\n"));
output->Append(wxT("			<li>KP_SUBTRACT</li>\n"));
output->Append(wxT("			<li>LEFT</li>\n"));
output->Append(wxT("			<li>MENU</li>\n"));
output->Append(wxT("			<li>NUM_LOCK</li>\n"));
output->Append(wxT("			<li>PAUSE</li>\n"));
output->Append(wxT("			<li>PGDN</li>\n"));
output->Append(wxT("			<li>PGUP</li>\n"));
output->Append(wxT("			<li>PRINT</li>\n"));
output->Append(wxT("			<li>RETURN</li>\n"));
output->Append(wxT("			<li>RIGHT</li>\n"));
output->Append(wxT("			<li>SCOLL_LOCK</li>\n"));
output->Append(wxT("			<li>SPACE</li>\n"));
output->Append(wxT("			<li>TAB</li>\n"));
output->Append(wxT("			<li>UP</li>\n"));
output->Append(wxT("		</ul>\n"));
output->Append(wxT("	</div>\n"));
output->Append(wxT("</div>\n"));
output->Append(wxT("<center>\n"));
output->Append(wxT("	<input type='button' value='Save' class='save' id='save' />\n"));
output->Append(wxT("</center>\n"));
output->Append(wxT("<script type='text/javascript' src='http://code.jquery.com/jquery-1.4.3.min.js'></script>\n"));
output->Append(wxT("<script type='text/javascript'>\n"));
output->Append(wxT("	// Show only the top level menus\n"));
output->Append(wxT("	$(\"tr\").hide();\n"));
output->Append(wxT("	$(\"tr.menu0, #header\").show();\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	// Remove blank menus\n"));
output->Append(wxT("	for(var c = 247; c > 0; c--) {\n"));
output->Append(wxT("		if($('tr.menu'+c).length === 0) {\n"));
output->Append(wxT("			$('#menu'+c).closest('tr').remove();\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("	}\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	// Have to recursively close all submenus as well\n"));
output->Append(wxT("	function close(menu) {\n"));
output->Append(wxT("		var openSubMenus = $('tr.'+menu+':visible');\n"));
output->Append(wxT("		for(var c = 0; c < openSubMenus.length; c++) {\n"));
output->Append(wxT("			var link = $(openSubMenus[c]).find('a');\n"));
output->Append(wxT("			link.html(\"&rarr;\");\n"));
output->Append(wxT("			close(link.attr('id'));\n"));
output->Append(wxT("		}\n"));
output->Append(wxT("		openSubMenus.hide();\n"));
output->Append(wxT("	}\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	// Open menus when clicked\n"));
output->Append(wxT("	$(\"a.expand\").live('click', function() {\n"));
output->Append(wxT("			var id = $(this).attr('id');\n"));
output->Append(wxT("			var rows = $(\"tr.\"+id);\n"));
output->Append(wxT("			\n"));
output->Append(wxT("			if(rows.is(\":visible\")) {\n"));
output->Append(wxT("				close(id);\n"));
output->Append(wxT("				rows.hide();\n"));
output->Append(wxT("				$(this).html(\"&rarr;\");\n"));
output->Append(wxT("			} else {\n"));
output->Append(wxT("				rows.show();\n"));
output->Append(wxT("				$(this).html(\"&darr;\");\n"));
output->Append(wxT("			}\n"));
output->Append(wxT("			\n"));
output->Append(wxT("			$(\"tr:visible:even\").removeClass(\"odd\").addClass(\"even\");\n"));
output->Append(wxT("			$(\"tr:visible:odd\").removeClass(\"even\").addClass(\"odd\");\n"));
output->Append(wxT("	});\n"));
output->Append(wxT("	\n"));
output->Append(wxT("	$(\"#save\").click(function() {\n"));
output->Append(wxT("		var bits = $(\"input.textfield\").map(function() { \n"));
output->Append(wxT("			var name = $(this).attr('name').replace(\"\\\"\", \"\\\\\\\"\");\n"));
output->Append(wxT("			var binding = $(this).val().replace(\"\\\"\", \"\\\\\\\"\");\n"));
output->Append(wxT("			if(binding.length == 0) return;\n"));
output->Append(wxT("			return [\"\\\"\", name, \"\\\"\", \":\", \"\\\"\", binding, \"\\\"\"].join(\"\");\n"));
output->Append(wxT("		});\n"));
output->Append(wxT("		var json = \"http://localhost/{\"+Array.prototype.join.call(bits, \",\")+\"}\";\n"));
output->Append(wxT("		window.location = json;\n"));
output->Append(wxT("	});\n"));
output->Append(wxT("</script>\n"));
output->Append(wxT("</body>\n"));
output->Append(wxT("</html>\n"));
  return output;
}